// Re-export everything the app needs from node_modules.
// Run: npx esbuild deps-entry.mjs --bundle --format=esm --outfile=libs/deps.js --platform=browser --minify
export { basicSetup, EditorView } from 'codemirror'
export { javascript } from '@codemirror/lang-javascript'
export { python } from '@codemirror/lang-python'
export { markdown as markdownLang } from '@codemirror/lang-markdown'
export { css } from '@codemirror/lang-css'
export { html } from '@codemirror/lang-html'
export { json } from '@codemirror/lang-json'
export { sql } from '@codemirror/lang-sql'
export { rust } from '@codemirror/lang-rust'
export { cpp } from '@codemirror/lang-cpp'
export { java } from '@codemirror/lang-java'
export { StreamLanguage } from '@codemirror/language'
export { julia } from '@codemirror/legacy-modes/mode/julia'
export { r } from '@codemirror/legacy-modes/mode/r'
export { oneDark } from '@codemirror/theme-one-dark'
export { default as Dexie } from 'dexie'
export { default as MarkdownIt } from 'markdown-it'
export { default as mdFootnote } from 'markdown-it-footnote'
export { default as mdDeflist } from 'markdown-it-deflist'
export { default as mdAttrs } from 'markdown-it-attrs'
export { generateKeyBetween } from 'fractional-indexing'
export { argon2id } from 'hash-wasm'
